### ISSUE TITLE
Exception when trying to view the Build Logging window

### ISSUE THREAD

**Issue by mqtwinter** [dotnet/project-system-tools#39] opened 2017-12-08 19:58 UTC
When I try to view the Build Logging window I get "Exception has been thrown by the target of an invocation".

I have VS 2017 15.5.1

![image](https://user-images.githubusercontent.com/27961202/33782831-286be78c-dc28-11e7-852c-51061f2f54d8.png)

**Comment by panopticoncentral** [comment] 2017-12-08 20:44
Duplicate of #36.

**Closed by panopticoncentral** 2017-12-08 20:44 UTC
